version: 2
jobs:
  build:
    docker:
      - image: testeng
    steps:
      - checkout
      - run:
          name: Testing testeng
          command: docker run --rm
      -v "$(pwd)"/selfdrive/test/tests/plant/out:/tmp/openpilot/selfdrive/test/tests/plant/out
      tmppilot /bin/sh -c 'cd /tmp/openpilot/selfdrive/test/tests/plant && OPTEST=1 ./test_longitudinal.py'
